name: Publish documentation

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

permissions: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    environment: docs-publish
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # tag: v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238  # tag: v6.2.0
        with:
          node-version: 22.12.x
          package-manager-cache: false
      - name: Install dependencies
        run: yarn --immutable
      - name: Build API documentation
        run: yarn build:docs
      - name: Azure login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ secrets.AZURE_OIDC_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_OIDC_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_OIDC_SUBSCRIPTION_ID }}
      - name: Upload to Azure Blob Storage
        uses: azure/cli@9f7ce6f37c31b777ec6c6b6d1dfe7db79f497956  # tag: v2.2.0
        with:
          inlineScript: | # zizmor: ignore[template-injection] This only runs on tags
            az storage blob upload-batch --account-name ${{ secrets.AZURE_ECOSYSTEM_PACKAGES_STORAGE_ACCOUNT_NAME }} -d '$web/get/${{ github.ref_name }}' -s ./docs --overwrite --auth-mode login
